[development]
dynaconf_merge = true
SOURCE_EMAIL_PASSWORD = "cjnlmlnywhfrjisp"

[development.security]
# openssl rand -hex 32
SECRET_KEY = "ONLYFORDEVELOPMENT"

[production]
dynaconf_merge = true
SOURCE_EMAIL_PASSWORD = "cjnlmlnywhfrjisp"

[production.security]
SECRET_KEY = "@vault path/to/vault/secret"

[testing]
dynaconf_merge = true

[testing.security]
SECRET_KEY = "ONLYFORTESTING"
