version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - health_notification_manager_DB__uri=postgresql://postgres:postgres@db:5432/health_notification_manager
      - health_notification_manager_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: health_notification_manager_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/health_notification_manager_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=health_notification_manager, health_notification_manager_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
